name: Linting

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  lint:
    name: Lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false

      - uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Confirm that it builds
        run: deno check ./src

      - name: Check deno fmt
        run: deno fmt --check
